language: scala
scala:
  - 2.13.1
  - 2.12.10
  - 2.11.12
jdk:
  - openjdk8

script: |
  sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: |
  sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.sbt/
